### PR TITLE
Implement `Line.flip` and `Line.flip_ip`

### LINKED ISSUE #115: Line.flip()
Switches points A and B around

### PR DESCRIPTION
**Pull request by avaxar**
Closes #115.

### CODE REVIEW

**Review by novialriptide — APPROVED** [review]
LGTM. I'm holding off on the merge awaiting another approval from 3 of our collaborators.

**Comment by novialriptide** [comment]
Ignore MacOS failing, it seems that it's on pygame's end due to some Python 3.11 vs pygame 2.1.2 bs.

**Review by novialriptide — CHANGES_REQUESTED** [review]
Looking back on this PR, I see that unit tests need to be made.

**Review by novialriptide — APPROVED** [review]
LGTM

**Review by Emc2356 — APPROVED** [review]
LGTM! and it seams like a useful feature.

**Pull request merged**
