### PR TITLE
Added circle.contains()

### PR DESCRIPTION
**Pull request by itzpr3d4t0r**
This PR adds the `circle.contains()` function to verify that a shape is inside the circle.

### CODE REVIEW

**Comment by novialriptide** [comment]
Shouldn't this be renamed to `collidecircle()`?

**Comment by itzpr3d4t0r** [comment]
> Shouldn't this be renamed to `collidecircle()`?

Unlike `collidecircle`, this function returns `True` only when the second circle is completely inside the first. `collidecircle()` returns `True` when the two circles are partially colliding whereas `contains` does not. This function reflects the `rect.contains()` function, that has the same use.

**Comment by itzpr3d4t0r** [comment]
Marking this as a draft as i want this function to work with any shape instead of just circle.

**Comment by itzpr3d4t0r** [comment]
Closing this because there are too many conflicts to resolve.

**Pull request closed without merging**
