### PR TITLE
Add another circle constructor

### PR DESCRIPTION
**Pull request by novialriptide**
Fixes: https://github.com/novialriptide/pygame_geometry/issues/62

### CODE REVIEW

**Comment by itzpr3d4t0r** [comment]
You should do the same but for the other branch in the function, the one with `PySequence_Check()`

**Comment by novialriptide** [comment]
> You should do the same but for the other branch in the function, the one with `PySequence_Check()`

What do you mean by "other branch in the function"?

**Comment by itzpr3d4t0r** [comment]
<https://github.com/novialriptide/pygame_geometry/pull/63/files#diff-ac4e813f079482c6454db108a4a2650020afeab43e9a6faec6ea13c9416af989R111-R137> add an `else if (length == 2)` in between those

**Comment by itzpr3d4t0r** [comment]
Past line 111 basically

**Review by Emc2356 — APPROVED** [review]
LGTM!
i really like the idea of having a constructor with the coordinates and then the radius.

**Comment by itzpr3d4t0r** [comment]
We should also add that 2 arguments handling to the fastcall version of `pgCircle_FromObject`: `pgCircle_FromObjectFastcall`

**Pull request merged**
