### PR TITLE
Polygon `insert_vertex()/remove_vertex()/pop_vertex()` and vertices assignment

### PR DESCRIPTION
**Pull request by itzpr3d4t0r**
You can now set a polygon vertices and add, remove or pop a vertex.

add a vertex
```Python
poly = Polygon([(1, 1), (2, 2), (3, 3)])
poly.insert_vertex(0, (0, 0))
poly -> [(0, 0), (1, 1), (2, 2), (3, 3)]
```
Change vertices on the fly
```Python
poly = Polygon([(1, 1), (2, 2), (3, 3)])
poly.vertices = [(4, 175), (24, 32), (54, 3),  (55, 33)]
```
remove a vertex
```Python
poly = Polygon([(1, 1), (2, 2), (3, 3), (4, 4)])
poly.remove_vertex(0)
poly -> [(2, 2), (3, 3), (4, 4)]
```
pop a vertex
```Python
poly = Polygon([(1, 1), (2, 2), (3, 3), (4, 4)])
vert = poly.pop_vertex(0)
poly -> [(2, 2), (3, 3), (4, 4)]
vert -> (1, 1)
```

### CODE REVIEW

**Comment by novialriptide** [comment]
I think `add_vertex()` should be renamed to `insert_vertex()`.

**Comment by itzpr3d4t0r** [comment]
Pls don't merge this, i want to align with the indexing behaviour of other python sequences, so the insert, remvoe and pop functions should all accept negative indexes and behave as expected.

**Comment by itzpr3d4t0r** [comment]
I guess it's fine now

**Comment by itzpr3d4t0r** [comment]
testing a new way to comment on PRs from the IDE

**Pull request merged**
